[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lv-loanword-detector"
version = "0.2.1"
description = "Latvian loanword classifier"
authors = [
    { name="Jorens Shtekels", email="jorens.stekels@outlook.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    # General dependencies.
    "pandas",
    "tqdm",
    # Entry extraction from the dict.
    "pymupdf",
    # Corpora extraction.
    "lxml",
    # Classifier and Labeling.
    "joblib",
    "scikit-learn",
    # Scripts.
    "requests",
    # Gui
    "coloredlogs",
    "tkinter-tooltip",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["integration", "scripts", "gui_integration", "classifiers"]

[project.scripts]
lvw-classify  = "classifier.classify:main"
lvw-example   = "integration.example:main"
lvw-download  = "scripts.download_models:main"
lvw-gui       = "gui_integration.main:main"
lvw-train-lm  = "classifiers.lm_rnn.train_:main"
lvw-train-gru = "classifiers.rnn.train_:main"
lvw-train-cnn = "classifiers.rnn.train_cnn:main"
lvw-encode    = "classifiers.lm_rnn.encode_word:main"

[project.optional-dependencies]
stanza = ["stanza>=1.10.0"]

[tool.setuptools.package-data]
scripts = ["current_models.txt"]
